/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AppEncuesta;
//forzar cambio

import javafx.application.Application;
import javafx.geometry.Side;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.Tab;
import javafx.scene.control.TabPane;
import javafx.scene.control.TabPane.TabClosingPolicy;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class AppEncuestas extends Application{
    
    @Override
    public void start(Stage PrimaryStage){
        //Crear TabPane
        TabPane tabPane = new TabPane();
        tabPane.setSide(Side.LEFT);//para que las pestañas aparezcan a la izquierda
        tabPane.setTabClosingPolicy(TabClosingPolicy.UNAVAILABLE);//para que no puedas cerrar las pestañas
     
        //Instanciar clases
        Home home = new Home();
        Academia academia = new Academia();
        Salud salud = new Salud();
        Deporte deporte = new Deporte();
        Poblacion poblacion = new Poblacion();
        
        //Crear pestañas
        Tab tabHome = new Tab();
        Tab tabAcademia = new Tab();
        Tab tabSalud = new Tab();
        Tab tabDeportes = new Tab();
        Tab tabPoblacion = new Tab();

        
        // HOME
        tabPane.getTabs().add(tabHome);
        Image homeImage = new Image("img/homeIco.png",20,20,false,false);
        ImageView imgHome = new ImageView(homeImage);
        tabHome.setGraphic(new Label("Home", imgHome));
        tabHome.setContent(home);
        // ACADEMIA
        tabPane.getTabs().add(tabAcademia);
        Image AcademicaImage = new Image("img/academicaIco.png",20,20,false,false);
        ImageView imgAcademica = new ImageView(AcademicaImage);
        tabAcademia.setGraphic(new Label("Académica", imgAcademica));
        tabAcademia.setContent(academia);
        // SALUD
        tabPane.getTabs().add(tabSalud);
        Image SaludImage = new Image("img/saludIco.png",20,20,false,false);
        ImageView imgSalud = new ImageView(SaludImage);
        tabSalud.setGraphic(new Label("Salud", imgSalud));
        tabSalud.setContent(salud);
        // DEPORTES
        tabPane.getTabs().add(tabDeportes);
        Image DeportesImage = new Image("img/deportesIco.png",20,20,false,false);
        ImageView imgDeportes = new ImageView(DeportesImage);
        tabDeportes.setGraphic(new Label("Deportes", imgDeportes));
        tabDeportes.setContent(deporte);
        // POBLACIÓN
        tabPane.getTabs().add(tabPoblacion);
        Image PoblacionImage = new Image("img/poblacionIco.png",20,20,false,false);
        ImageView imgPoblacion = new ImageView(PoblacionImage);
        tabPoblacion.setGraphic(new Label("Población", imgPoblacion));
        tabPoblacion.setContent(poblacion);


        VBox vBox = new VBox(tabPane);
        Scene scene = new Scene(vBox);
        PrimaryStage.setScene(scene);
        
        //Estilo
        scene.getStylesheets().add(getClass().getResource("Style.css").toExternalForm()); 
        
        
        //Título
        PrimaryStage.setTitle("ENCUESTAS");
        PrimaryStage.show();
        
    }
   

    public static void main(String[] args) {
       launch(args);
    }
}
