/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AppEncuesta;

//import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;

//class AppEncuestasTest {
//    @Test void appHasAGreeting() {
//        AppEncuestas classUnderTest = new AppEncuestas();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
//}
